name       : shared-mime-info
version    : '1.9'
release    : 8
source     :
    - http://freedesktop.org/~hadess/shared-mime-info-1.9.tar.xz : 5c0133ec4e228e41bdf52f726d271a2d821499c2ab97afd3aa3d6cf43efcdc83
license    : GPL-3.0
summary    : Shared Mime Info Database
component  : desktop.core
description: |
    The Shared Mime Info package contains a MIME database. This allows central updates of MIME information for all supporting applications.
patterns   :
    - /usr/share/pkgconfig
setup      : |
    %configure --disable-update-mimedb
build      : |
    %make -j1
install    : |
    %make_install
