name       : shared-mime-info
version    : '1.8'
release    : 7
source     :
    - http://freedesktop.org/~hadess/shared-mime-info-1.8.tar.xz : 2af55ef1a0319805b74ab40d331a3962c905477d76c086f49e34dc96363589e9
license    : GPL-3.0
summary    : Shared Mime Info Database
component  : desktop.core
description: |
    The Shared Mime Info package contains a MIME database. This allows central updates of MIME information for all supporting applications.
patterns   :
    - /usr/share/pkgconfig
setup      : |
    %configure
build      : |
    %make -j1
install    : |
    %make_install
