name        : shared-mime-info
version     : 1.5
release     : 5
source     :
    - http://people.freedesktop.org/~hadess/shared-mime-info-1.5.tar.xz : d6412840eb265bf36e61fd7b6fc6bea21b0f58cb22bed16f2ccccdd54bea4180
license     :
    - GPL-3.0
summary     : Shared Mime Info Database
description : |
    The Shared Mime Info package contains a MIME database. This allows central updates of MIME information for all supporting applications.
patterns   :
    - /usr/share/pkgconfig
setup      : |
    %configure
build      : |
    %make -j1
install    : |
    %make_install
