name       : shared-mime-info
version    : '2.0'
release    : 9
source     :
    - https://gitlab.freedesktop.org/xdg/shared-mime-info/uploads/0440063a2e6823a4b1a6fb2f2af8350f/shared-mime-info-2.0.tar.xz : 23c1cb7919f31cf97aeb5225548f75705f706aa5cc7d1c4c503364bcc8681e06
license    : GPL-3.0-or-later
summary    : Shared Mime Info Database
component  : desktop.core
description: |
    The Shared Mime Info package contains a MIME database. This allows central updates of MIME information for all supporting applications.
builddeps  :
    - git
    - itstool
    - xmlto
patterns   :
    - /*
setup      : |
    # Binary diff so need to use this instead of %patch
    git apply -p1 < $pkgfiles/Remove-ELF-magic.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
