name       : shared-mime-info
version    : '2.2'
release    : 11
source     :
    - https://gitlab.freedesktop.org/xdg/shared-mime-info/-/archive/2.2/shared-mime-info-2.2.tar.bz2 : 418c480019d9865f67f922dfb88de00e9f38bf971205d55cdffab50432919e61
license    : GPL-3.0-or-later
summary    : Shared Mime Info Database
component  : desktop.core
description: |
    The Shared Mime Info package contains a MIME database. This allows central updates of MIME information for all supporting applications.
patterns   :
    - /*
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
