name       : shared-mime-info
version    : 1.7
release    : 6
source     :
    - http://freedesktop.org/~hadess/shared-mime-info-1.7.tar.xz : eacc781cfebaa2074e43cf9521dc7ab4391ace8a4712902b2841669c83144d2e
license    :
    - GPL-3.0
summary    : Shared Mime Info Database
component  : desktop.core
description: |
    The Shared Mime Info package contains a MIME database. This allows central updates of MIME information for all supporting applications.
patterns   :
    - /usr/share/pkgconfig
setup      : |
    %configure
build      : |
    %make -j1
install    : |
    %make_install
